'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function load(){const ctx={};ctx.window=ctx;vm.createContext(ctx);for(const f of ['model','customize'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../js/'+f+'.js'),'utf8'),ctx);return ctx.SF;}
test('formatting preserves plain text, survives normalization and follows insertions',()=>{const SF=load(),s=SF.makeSlide('content');s.title='Explain this idea';SF.Custom.apply(s,'title',8,12,'bold',true);SF.Custom.rebase(s,'title',s.title,'Please explain this idea');s.title='Please explain this idea';const restored=SF.normalizeSlide(JSON.parse(JSON.stringify(s)));assert.equal(restored.title,'Please explain this idea');const mark=SF.Custom.entry(restored,'title').marks[0];assert.equal(restored.title.slice(mark.start,mark.end),'this');});
test('clearing a selected range preserves surrounding emphasis and stale metadata cannot style different text',()=>{const SF=load(),s=SF.makeSlide('content');s.title='abcdefgh';SF.Custom.apply(s,'title',0,8,'bold',true);SF.Custom.apply(s,'title',2,6,'clear');assert.equal(JSON.stringify(SF.Custom.entry(s,'title').marks.map(m=>[m.start,m.end])),'[[0,2],[6,8]]');s.title='different';assert.equal(SF.Custom.entry(s,'title').marks.length,0);});
test('layout changes, previews and swaps use the same content-preserving rules',()=>{const SF=load(),original=SF.makeSlide('content');original.title='Same lesson';original.bullets=['First','Second'];const preview=SF.prepareLayout(SF.normalizeSlide(JSON.parse(JSON.stringify(original))),'table');assert.match(preview.body,/Term/);assert.equal(original.body,'');SF.prepareLayout(original,'table');assert.equal(original.body,preview.body);SF.prepareLayout(original,'content');assert.deepEqual(Array.from(original.bullets),['First','Second']);SF.setImagePlacement(original,'top');SF.swapImagePlacement(original);assert.equal(SF.imagePlacement(original),'bottom');SF.setImagePlacement(original,'left');SF.swapImagePlacement(original);assert.equal(SF.imagePlacement(original),'right');});
test('learner excerpts contain only content visible in the selected layout',()=>{const SF=load(),s=SF.makeSlide('content');s.bullets=['First','Second'];s.body='Old quote';s.subtitle='Opening';s.progressive=true;assert.equal(SF.slideExcerpt(s,1),'First');s.type='title';assert.equal(SF.slideExcerpt(s,0),'Opening');s.type='video';assert.equal(SF.slideExcerpt(s,0),'');s.type='quote';s.progressive=false;assert.equal(SF.slideExcerpt(s,0),'Old quote');s.type='table';s.progressive=true;s.body='Name | Value\nA | 1\nB | 2';assert.equal(SF.slideSteps(s).length,2);assert.equal(SF.slideExcerpt(s,1),'Name · Value\nA · 1');});
test('progressive builds step quote lines and explain paragraphs',()=>{const SF=load(),q=SF.makeSlide('quote');q.body='Line one\nLine two\n\nLine three';q.progressive=true;assert.deepEqual(Array.from(SF.slideSteps(q)),['Line one','Line two','Line three']);assert.equal(SF.slideExcerpt(q,1),'Line one');assert.equal(SF.slideExcerpt(q,2),'Line one\nLine two');const e=SF.makeSlide('explain');e.body='First paragraph.\n\nSecond paragraph.';e.progressive=true;assert.deepEqual(Array.from(SF.slideSteps(e)),['First paragraph.','Second paragraph.']);assert.equal(SF.slideExcerpt(e,1),'First paragraph.');});
test('presenter answer labels support every compiled input kind',()=>{const SF=load();assert.equal(SF.correctAnswerLabel({input:'choice',options:['One','Two'],correct:1}),'B — Two');assert.equal(SF.correctAnswerLabel({input:'text',answer:'Paris',options:[]}),'Paris');assert.equal(SF.correctAnswerLabel({input:'number',answer:'0 °C',options:[]}),'0 °C');});
test('removing a bullet preserves formatting on the following points',()=>{const SF=load(),s=SF.makeSlide('content');s.bullets=['First','Second'];SF.Custom.apply(s,'bullets.1',0,6,'bold',true);SF.Custom.removeBullet(s,0);assert.equal(s.bullets[0],'Second');assert.equal(SF.Custom.entry(s,'bullets.0').marks.length,1);});
